project:
  type: website

website:
  title: "quatro572hw_week_four"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: index2.qmd
        text: SweetHome
      - href: index3.qmd
        text: HomelessHome
      - href: project_start.qmd
        text: MisterRodrigez'sProject
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

