project:
  type: website

website:
  title: "STAT570 - Luxembourg Project"
  navbar:
    left:
      - href: index.qmd
        text: Altan's Home
      - href: index2.qmd
        text: Çağatay's Computer
      - href: project_start.qmd
        text: Mr Alican's Coca-Cola Car
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

